include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

formatter:
  page_width: 120

linter:
  rules:
    lines_longer_than_80_chars: false
    public_member_api_docs: false
